### PR TITLE
ETH-126: name and symbol changing

### PR DESCRIPTION
**Pull request by jtakalai**

### CODE REVIEW

**Review by hpihkala — COMMENTED** [review]
LGTM otherwise, but I didn't dig deeper into what the OZ code does with the name and symbol, so they are questions worth answering perhaps:

- What does the `ERC20` constructor do with the name and symbol?
- What does the `ERC20Permit` do with the name?

**Comment by jtakalai** [comment]
> * What does the `ERC20` constructor do with the name and symbol?

stores them and gives them out in getters, nothing else

> * What does the `ERC20Permit` do with the name?

it's used as a "EIP 712 domain separator" to distinguish the contract from other contracts so that signatures for one can't be used in another. The suggestion was to use the token name there, probably presuming it's going to be unique-ish. That it can't be changed later doesn't feel like a huge issue, but requiring the change really would mean OpenZeppelin's code can't be used.

**Comment by hpihkala** [comment]
Did I understand correctly: if we change the name, it will break `permit` from that point onwards?

**Comment by jtakalai** [comment]
> Did I understand correctly: if we change the name, it will break `permit` from that point onwards?

No, I don't believe it would, because anyone who creates a signature would use the same old domain separator. Signing would work just fine no matter the domain separator is, just it's a recommendation to use the token name so that the domains are separate. But even if domains were not separate, it wouldn't make it simple to abuse signatures to one token in another. So that's really a non-issue as far as I can tell.

**Comment by hpihkala** [comment]
Yeah ok I see. Would be good to add this in then, makes things more future-proof.

**Review by Isentrope1 — APPROVED** [review]

**Pull request merged**
